### ISSUE TITLE
Feature request: save indented

### ISSUE THREAD

**Issue by Kralizek** [sleeuwen/dotnet-json#2]
It would be great if this tool allowed to quickly load the content of a file and saved it as "indented".

Example:

Given `sample.json`
```json
{"hello":"world","answer": 42}
```

```
dotnet json indent sample.json
```

```json
{
  "hello": "world",
  "answer": 42
}
```

**Comment by sleeuwen** [comment]
Hi Kralizek,

Thanks for your interest in dotnet-json. I like your idea and have released a new version, 0.5.0, that includes the `dotnet json indent` command. Update the global tool to the latest version and try it out!

If you have any issues with the implementation, feel free to reopen the issue.
