### ISSUE TITLE
Merge fails for arrays

### ISSUE THREAD

**Issue by goldsam** [sleeuwen/dotnet-json#5]
The tool fails to merge arrays by replacing many array elements with `null` in the merged output.

**Comment by sleeuwen** [comment]
Hi @goldsam , thanks for reporting the issue but I'm having trouble reproducing it. Could you provide an example with the contents of the two files you are trying to merge?

**Comment by goldsam** [comment]
My needs have evolved to be a bit more complicated. I'm going to use JSON PATCH instead.
